name: Niv update
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  niv-update:
    name: Update all niv sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: cachix/install-nix-action@v10
    - name: Run niv update
      run: nix-shell --run "niv update"
    - name: Commit updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Automatic niv update" -a
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
